/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.64
 * Generated at: 2021-05-08 17:09:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!-- 상품넘버 받아오기 -->\r\n");
      out.write("    ");

    	int pnum = Integer.parseInt(request.getParameter("pnum")); //상품목록에서 상품을 클릭하면 해당하는 상품페이지를 넘겨주고 여기서 받는다
    												//자바스크립트에서 사용될 pnum은 request받은 값을 Body로 넘겨준 후 input hidden을 통해 다시 스크립트로 
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"resources/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom fonts for this template -->\r\n");
      out.write("<link href=\"resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"resources/vendor/bootstrap/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"resources/vendor/fontawesome-free/css/all.min.css/vendor/simple-line-icons/css/simple-line-icons.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"resources/css/landing-page.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"resources/css/landing-page.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("<!-- 제이쿼리 -->\r\n");
      out.write("<script type=\"text/javascript\" src = \"resources/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Include the plugin's CSS and JS: -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/bootstrap-multiselect.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap-multiselect.css\" type=\"text/css\"/>\r\n");
      out.write("<!-- Initialize the plugin: -->\r\n");
      out.write("\r\n");
      out.write("<!-- 카카오맵API 라이브러리 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=a928be6ed8a88c1ba98215dcf28ec6f0&libraries=services,clusterer,drawing\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t//넘어온 상품번호로 상품테이블에 접근해서 주소를 가져옴 => 주소를 위도/경도로 바꾸고 그걸 지도의 중심으로 표시 + 편의시설 데이터를 지도에 찍어주기\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar pnum = $(\"#pnum\").val() //이전 페이지(상품목록)에서 넘어온 상품번호를 받아주는 부분\r\n");
      out.write("\t\tconsole.log(\"상품번호 확인: \",pnum)\r\n");
      out.write("\t\tvar pname;\r\n");
      out.write("\t\tvar address;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t//매물정보 받아올 AJAX\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t수정할 부분\r\n");
      out.write("\t\t\t상품컨트롤러로 상품번호를 보내 상품 받아오기\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\turl: \"productInfo\", //매물번호를 통해서 상품정보를 가져온다\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tpnum : pnum,\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync:false, //이거 추가하면 결과값을 전역변수에 담아서 사용가능!!!\r\n");
      out.write("\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\tconsole.log(\"결과 확인: \", result)\r\n");
      out.write("\t\t\t\tpname = result.pname //매물명 : 리모델링된 원룸\r\n");
      out.write("\t\t\t\tptype = result.ptype //매물타입 : 아파트\r\n");
      out.write("\t\t\t\tctype = result.ctype\t//거래형태 : 매매\r\n");
      out.write("\t\t\t\tprice = result.price\t//가격 : 500/42만원\r\n");
      out.write("\t\t\t\taddress = result.address\t//매물주소 : 서울특별시 서대문구 연세로 2길 17\r\n");
      out.write("\t\t\t\taddress1 = result.address1\t//상세주소 : 1동 102호\r\n");
      out.write("\t\t\t\tcontact = result.contact\t//판매자 전화번호 : 010-5412-1315\r\n");
      out.write("\t\t\t\tfloor = result.floor\t//매물층,건물층 : 4층/5층\r\n");
      out.write("\t\t\t\trsize = result.rsize //전용 면적 : 16.5㎡\r\n");
      out.write("\t\t\t\troom = result.room\t//방개수/화장실수 : 3개/2개\r\n");
      out.write("\t\t\t\ttotal = result.total //총세대수 : 30세대\r\n");
      out.write("\t\t\t\tplacetype = result.placetype\t//세권 : 역세권\r\n");
      out.write("\t\t\t\troomimg = result.roomimg\t//방사진 : 001.jpg\r\n");
      out.write("\t\t\t\troomimg2 = result.roomimg2\t//방사진 : 001.jpg\r\n");
      out.write("\t\t\t\troomimg3 = result.roomimg3\t//방사진 : 001.jpg\r\n");
      out.write("\t\t\t\tpinfo = result.pinfo\t\t//방상세설명 : 신촌역 2호선 지하철역과 도보로 3분 거리에 위치한 원룸입니다\r\n");
      out.write("\t\t\t\tdstatue = result.dstatue\t//거래상태 : 협의중\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\".pname\").html(pname)\r\n");
      out.write("\t\t\t\t$(\".ctype\").html(ctype)\r\n");
      out.write("\t\t\t\t$(\".price\").html(price)\r\n");
      out.write("\t\t\t\t$(\".rsize\").html(rsize)\r\n");
      out.write("\t\t\t\t$(\".contact\").html(contact)\r\n");
      out.write("\t\t\t\t$(\".dstatue\").html(dstatue)\r\n");
      out.write("\t\t\t\t$(\".floor\").html(floor)\r\n");
      out.write("\t\t\t\t$(\".room\").html(room)\r\n");
      out.write("\t\t\t\t$(\".placetype\").html(placetype)\r\n");
      out.write("\t\t\t\t$(\"#roomimg\").html(\"<img src = 'resources/rimg/\"+roomimg+\"'style = 'width:900px; height:599px;'>\")\r\n");
      out.write("\t\t\t\t$(\"#roomimg2\").html(\"<img src = 'resources/rimg/\"+roomimg2+\"'style = 'width:500px; height:290px;'>\")\r\n");
      out.write("\t\t\t\t$(\"#roomimg3\").html(\"<img src = 'resources/rimg/\"+roomimg3+\"'style = 'width:500px; height:305px'>\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\tconsole.log(\"매물명 확인하기: \",pname)\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//편의시설에 대한 위치정보를 담을 전역변수 선언\r\n");
      out.write("\t\tcsLatitude = []\r\n");
      out.write("\t\tcsLongtitude = []\r\n");
      out.write("\t\tcctvLatitude = []\r\n");
      out.write("\t\tcctvLongtitude = []\r\n");
      out.write("\t\tindex = 0 //배열 인덱스 카운트를 위한 변수 선언\r\n");
      out.write("\t\tindex1 = 0//배열 인덱스 카운트를 위한 변수 선언\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"getFlocation\",\r\n");
      out.write("\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\tconsole.log(result)\r\n");
      out.write("\t\t\t\t//result에 편의시설에 대한 위치정보가 다 들어있음(편의점, cctv) ~> 따라서 분류(편의점, cctv)를 통해 나눠준 후 \r\n");
      out.write("\t\t\t\tfor (let i = 0; i < result.length; i++) {\r\n");
      out.write("\t\t\t\t\tif(result[i].name == \"cs\"){\r\n");
      out.write("\t\t\t\t\t\tcsLatitude[index] = result[i].latitude\r\n");
      out.write("\t\t\t\t\t\tcsLongtitude[index] = result[i].longtitude\r\n");
      out.write("\t\t\t\t\t\tindex++\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else if(result[i].name == \"cctv\"){\r\n");
      out.write("\t\t\t\t\t\tcctvLatitude[index1] = result[i].latitude\r\n");
      out.write("\t\t\t\t\t\tcctvLongtitude[index1] = result[i].longtitude\r\n");
      out.write("\t\t\t\t\t\tindex1++\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\tAJAX를 통해 받아온 상품주소 & 편의시설 위치정보를 KAKAO맵에 띄어주기\r\n");
      out.write("\t\t1. 상품주소(도로명/지번)를 geocoder를 사용하여 위도/경도로 변경\r\n");
      out.write("\t\t2. addressSearch메서드를 활용하여 변경된 위도/경도로 지도에 찍어주기\r\n");
      out.write("\t\t*/\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar geocoder = new kakao.maps.services.Geocoder(); //geocoder : 주소를 입력하면 위도와 경도로 바꿔주는 객체\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgeocoder.addressSearch(address, function(result, status) {\r\n");
      out.write("\t\t\tif(status === kakao.maps.services.Status.OK){\r\n");
      out.write("\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\tvar coords = new kakao.maps.LatLng(result[0].y, result[0].x); //변경된 위도경도를 담은 변수\r\n");
      out.write("\t\t\t\tconsole.log(coords)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar mapContainer = $('#map')[0], // 지도를 표시할 div \r\n");
      out.write("\t\t\t\tmapOption = {\r\n");
      out.write("\t\t\t\t\tcenter : new kakao.maps.LatLng(result[0].y, result[0].x), // 지도의 중심좌표(  =>  해당 상품 위도/경도로 바꾸기)\r\n");
      out.write("\t\t\t\t\tlevel : 3\r\n");
      out.write("\t\t\t\t// 지도의 확대 레벨3\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tvar map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//편의시설/ 안전시설 버튼을 누르면 화면에 위치정보를 띄어준다 \r\n");
      out.write("\t\t\t\t//***********************궁금한점!!! 이 아래코드를 원생성 코드보다 뒤에 넣으면 생성이 안됨**********************************\r\n");
      out.write("\t\t\t\tif ($(\"#b2\").click(function() {\r\n");
      out.write("\t\t\t\t \t//마커에 이미지 입히기\r\n");
      out.write("\t\t\t\t\tvar imageSrc = 'https://www.urbanbrush.net/web/wp-content/uploads/edd/2018/02/web-20180209042218641969.png', // 마커이미지의 주소입니다    \r\n");
      out.write("\t\t\t\t\timageSize = new kakao.maps.Size(30, 30), // 마커이미지의 크기입니다\r\n");
      out.write("\t\t\t\t\timageOption = {\r\n");
      out.write("\t\t\t\t\t\toffset : new kakao.maps.Point(27, 69)\r\n");
      out.write("\t\t\t\t\t}; // 마커이미지의 옵션입니다. 마커의 좌표와 일치시킬 이미지 안에서의 좌표를 설정합니\r\n");
      out.write("\t\t\t\t\tvar markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imageOption)\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfor (let i = 0; i < csLatitude.length; i++) { //편의시설 배열 길이\r\n");
      out.write("\t\t\t\t\t\t// 마커가 표시될 위치입니다 \r\n");
      out.write("\t\t\t\t\t\tmarkerPosition = new kakao.maps.LatLng(csLatitude[i], csLongtitude[i]); //편의시설 위도/경도 정보\r\n");
      out.write("\t\t\t\t\t\t// 마커를 생성합니다\r\n");
      out.write("\t\t\t\t\t\tvar marker = new kakao.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\tposition : markerPosition,\r\n");
      out.write("\t\t\t\t\t\t\timage : markerImage\r\n");
      out.write("\t\t\t\t\t\t// 마커이미지 설정 \r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t// 마커가 지도 위에 표시되도록 설정합니다\r\n");
      out.write("\t\t\t\t\t\tmarker.setMap(map);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}))\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif ($(\"#b3\").click(function() {\r\n");
      out.write("\t\t\t\t\t//마커에 이미지 입히기\r\n");
      out.write("\t\t\t\t\tvar imageSrc = 'https://www.urbanbrush.net/web/wp-content/uploads/edd/2018/02/web-20180221070608779012.png', // 마커이미지의 주소입니다    \r\n");
      out.write("\t\t\t\t\timageSize = new kakao.maps.Size(30, 30), // 마커이미지의 크기입니다\r\n");
      out.write("\t\t\t\t\timageOption = {\r\n");
      out.write("\t\t\t\t\t\toffset : new kakao.maps.Point(27, 69)\r\n");
      out.write("\t\t\t\t\t}; // 마커이미지의 옵션입니다. 마커의 좌표와 일치시킬 이미지 안에서의 좌표를 설정합니\r\n");
      out.write("\t\t\t\t\tvar markerImage = new kakao.maps.MarkerImage(\r\n");
      out.write("\t\t\t\t\t\t\timageSrc, imageSize, imageOption)\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfor (let i = 0; i < cctvLatitude.length; i++) {//안전시설 배열 길이\r\n");
      out.write("\t\t\t\t\t\t// 마커가 표시될 위치입니다 \r\n");
      out.write("\t\t\t\t\t\tmarkerPosition = new kakao.maps.LatLng(\r\n");
      out.write("\t\t\t\t\t\t\t\tcctvLatitude[i], cctvLongtitude[i]); //안전시설 위도/경도 정보\r\n");
      out.write("\t\t\t\t\t\t// 마커를 생성합니다\r\n");
      out.write("\t\t\t\t\t\tvar marker = new kakao.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\tposition : markerPosition,\r\n");
      out.write("\t\t\t\t\t\t\timage : markerImage\r\n");
      out.write("\t\t\t\t\t\t// 마커이미지 설정 \r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t// 마커가 지도 위에 표시되도록 설정합니다\r\n");
      out.write("\t\t\t\t\t\tmarker.setMap(map);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}))\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 지도에 표시할 원을 생성합니다\r\n");
      out.write("\t\t\t\tvar circle = new kakao.maps.Circle({\r\n");
      out.write("\t\t\t\t\tcenter : new kakao.maps.LatLng(result[0].y, result[0].x), // 원의 중심좌표 입니다 \r\n");
      out.write("\t\t\t\t\tradius : 50, // 미터 단위의 원의 반지름입니다 \r\n");
      out.write("\t\t\t\t\tstrokeWeight : 5, // 선의 두께입니다 \r\n");
      out.write("\t\t\t\t\tstrokeColor : '#75B8FA', // 선의 색깔입니다\r\n");
      out.write("\t\t\t\t\tstrokeOpacity : 1, // 선의 불투명도 입니다 1에서 0 사이의 값이며 0에 가까울수록 투명합니다\r\n");
      out.write("\t\t\t\t\tstrokeStyle : 'dashed', // 선의 스타일 입니다\r\n");
      out.write("\t\t\t\t\tfillColor : '#CFE7FF', // 채우기 색깔입니다\r\n");
      out.write("\t\t\t\t\tfillOpacity : 0.7\r\n");
      out.write("\t\t\t\t// 채우기 불투명도 입니다   \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t// 지도에 원을 표시합니다 \r\n");
      out.write("\t\t\t\tcircle.setMap(map);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t<장바구니 버튼>\r\n");
      out.write("\t\t장바구니 버튼을 누른 경우 \r\n");
      out.write("\t\t1. (기본적으로)상품페이지로 넘어오면 pnum과 세션처리된 아이디, like에 0을 마이페이지 컨트롤러로 보내준다 \r\n");
      out.write("\t\t2. (상품담기버튼 누른경우)pnum , 세션처리된 아이디, like에 1을 담아 보내준다\r\n");
      out.write("\t\t*/\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar userid = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' //");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("라고 하면 안넘어감.....\r\n");
      out.write("\t\tvar liked = 0\r\n");
      out.write("\t\tconsole.log(\"liked: \",liked)\r\n");
      out.write("\t\tconsole.log(\"userid: \", userid)\r\n");
      out.write("\t\t//상품페이지로 넘어오면 자동적으로 최근방문페이지 카운트를 위해 AJAX를 이용하여 마이페이지 컨트롤러로 정보들을 넘겨준다\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"my_insert\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\tpnum : pnum,\r\n");
      out.write("\t\t\t\tuserid : userid,\r\n");
      out.write("\t\t\t\tliked : liked,\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function() {\r\n");
      out.write("\t\t\t\tconsole.log(\"최근방문페이지\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//장바구니 버튼을 누른 경우\r\n");
      out.write("\t\t//AJAX를 통해 해당 아이디와 상품넘버, like=1 보내줌 ~> 마이페이지 컨트롤러로 ~> insert SQL수행\r\n");
      out.write("\t\t$(\"#b1\").click(function() {\r\n");
      out.write("\t\t\talert(\"장바구니에 담겼습니다\")\r\n");
      out.write("\t\t\tliked = 1\r\n");
      out.write("\t\t\tconsole.log(\"pnum: \",pnum)\r\n");
      out.write("\t\t\tconsole.log(\"userid: \",userid)\r\n");
      out.write("\t\t\tconsole.log(\"liked: \",liked)\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"basket\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\tpnum : pnum,\r\n");
      out.write("\t\t\t\t\tuserid : userid,\r\n");
      out.write("\t\t\t\t\tliked : liked,\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess: function() {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"찜하기\")\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t/* 비로그인 상태에서 장바구니 버튼을 눌렀을 때 로그인 페이지로 전환 */\r\n");
      out.write("\t$(\"#b4\").click(function(){\r\n");
      out.write("\t\talert(\"로그인이 필요한 서비스입니다.\")\r\n");
      out.write("\t\tconsole.log(\"hid\")\r\n");
      out.write("\t\tlocation.href = \"ruser_login.jsp\"\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t$(\"#b5\").click(function(){\r\n");
      out.write("\t\talert(pinfo)\r\n");
      out.write("\t});\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".a{\r\n");
      out.write("\tdisplay: inline-block; /* div 수평정렬 */\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write(".b{\r\n");
      out.write("\tdisplay: inline-block; /* div 수평정렬 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic{\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<input id = \"pnum\" type =\"hidden\" value=");
      out.print(pnum);
      out.write(">\r\n");
      out.write("<!-- Navigation : 위에 부분-->\r\n");
      out.write("\t<nav class=\"navbar navbar-light bg-light static-top\">\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"main.jsp\">내 집은 신촌에 있나방</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"menu\">\r\n");
      out.write("\t\t <!-- 세션처리 -->\r\n");
      out.write("\t\t <!-- 세션처리된 아이디가 있는경우 -> 로그인된 상태 -->\r\n");
      out.write("\t\t");
 if(session.getAttribute("userid") == null){ 
      out.write("\r\n");
      out.write("\t\t <a class=\"btn btn-primary btn-lg\" href=\"productSummary.jsp\">방찾기</a>\r\n");
      out.write("\t\t <a class=\"btn btn-primary btn-lg\" href=\"ruser_login.jsp\">마이페이지</a> <!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("\t\t <a class=\"btn btn-primary btn-lg\" href=\"qnamain.jsp\">고객센터</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("\t\t <a class=\"btn btn-primary btn-lg\" href=\"ruser_select.jsp\">회원정보검색</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("\t\t<a class=\"btn btn-primary btn-lg\" href=\"ruser_login.jsp\">로그인</a>\r\n");
      out.write("\t\t<a class=\"btn btn-primary btn-lg\" href=\"signup.jsp\">회원가입</a>\r\n");
      out.write("\t\t<!-- 세션처리된 아이디가 없는경우 -> 로그인 x -->\r\n");
      out.write("\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t <a class=\"btn btn-primary btn-lg\" href=\"productSummary.jsp\">방찾기</a>\r\n");
      out.write("\t\t <a class=\"btn btn-primary btn-lg\" href=\"mypage_main.jsp\">마이페이지</a> <!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("\t\t <a class=\"btn btn-primary btn-lg\" href=\"PMain.jsp\">방내놓기</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("\t\t <a class=\"btn btn-primary btn-lg\" href=\"qnamain.jsp\">고객센터</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("\t\t <a class=\"btn btn-primary btn-lg\" href=\"ruser_update.jsp\">회원정보수정</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("\t\t <a class=\"btn btn-primary btn-lg\" href=\"ruser_delete.jsp\">회원탈퇴</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("\t\t<a class=\"btn btn-primary btn-lg\" href=\"ruser_logout.jsp\">로그아웃</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("\t\t<div class=\"btn btn-primary btn-lg\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 환영합니다.</div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<div class = \"content\" style=\"padding-left: 250px; padding-right: 200px\">\r\n");
      out.write("\t\t<div class = \"contentTop\" style=\"width: 1405px; height: 150px; margin-top: 50px\"> <!-- 크기고정 width고정시켜버림 -->\r\n");
      out.write("\t\t\t<div class = \"a\">\r\n");
      out.write("\t\t\t\t<span class = \"pname\" style=\"font-size: 30px; font-weight: bold\"></span> <br>\r\n");
      out.write("\t\t\t\t<span class = \"ctype\" style=\"font-weight: bold\"></span>&nbsp&nbsp<span class = \"price\" style=\"font-weight: bold\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class = \"a\">\r\n");
      out.write("\t\t\t\t\t<span style=\"font-size: 30px; font-weight: bold\">전용면적</span><br>\r\n");
      out.write("\t\t\t\t\t<span class = \"rsize\" style=\"font-weight: bold\"></span><span style=\"font-size: 15px; font-weight: bold\">㎡</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"a\">\r\n");
      out.write("\t\t\t\t<span class =\"placetype\" style=\"font-size: 30px; font-weight: bold;margin-top: 100px\"></span><br>\r\n");
      out.write("\t\t\t\t<span> </span><br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"a\" style=\"float: right; width: 300px; height: 50px;\">\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 20px; font-weight: bold\">주)래미안복덕방부동산중개법인</span><br>\r\n");
      out.write("\t\t\t\t<span style=\"font-weight: bold\">김미희</span>(<span class = \"contact\" style=\"font-weight: bold\"></span>)<br>\r\n");
      out.write("\t\t\t\t<span style=\"font-weight: bold\">거래현황: </span><span class = \"dstatue\" style=\"font-weight: bold\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id = \"a\"><!-- 장바구니 테이블 -->\r\n");
      out.write("\t\t\t");
if(session.getAttribute("userid")!=null){ 
      out.write(" <!-- 세션처리된 아이디가 있는경우 -> 로그인된 상태 -->\r\n");
      out.write("\t\t\t\t<button id = \"b1\" style=\"background-color:#007bff; color: white\">\r\n");
      out.write("\t\t\t\t\t상품담기\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<button id = \"b4\" style=\"background-color:#007bff; color: white\">\r\n");
      out.write("\t\t\t\t\t상품담기\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t<button id =\"b5\" style=\"background-color:#007bff; color: white\">상품상세설명</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr color=\"#007bff\" size = \"5\" style=\"padding-bottom: 5px\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id = \"contentMid\" style=\"width: 700px\">\r\n");
      out.write("\t\t\t<div class = \"b\">\r\n");
      out.write("\t\t\t\t해당층/건물층&nbsp&nbsp&nbsp&nbsp<span class = \"floor\" style=\"font-weight: bold\"></span><span style=\"font-size: 15px; font-weight: bold\">층</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"b\" style=\"margin-left: 50px\">\r\n");
      out.write("\t\t\t\t전용/공급면적&nbsp&nbsp&nbsp&nbsp<span class = \"rsize\" style=\"font-weight: bold\"></span><span style=\"font-size: 15px; font-weight: bold\">㎡</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"b\" style=\"margin-left: 50px\">\r\n");
      out.write("\t\t\t\t방수/욕실수&nbsp&nbsp&nbsp&nbsp<span class = \"room\" style=\"font-weight: bold\"></span><span style=\"font-size: 15px; font-weight: bold\">개</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div class = \"b\">\r\n");
      out.write("\t\t\t\t난방종류&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp\r\n");
      out.write("\t\t\t\t<span style=\"font-weight: bold\">개별난방</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"b\" style=\"margin-left: 42px\">\r\n");
      out.write("\t\t\t\t주차대수&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp\r\n");
      out.write("\t\t\t\t<span style=\"font-weight: bold\">총 1대</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"b\" style=\"margin-left: 60px\">\r\n");
      out.write("\t\t\t\t입주가능일&nbsp&nbsp&nbsp&nbsp\r\n");
      out.write("\t\t\t\t<span style=\"font-weight: bold\">즉시입주</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id = \"contentBot\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<!-- 브라우저에서 컨트롤러를 통해 넘어온 값(db에서 가져온 값(sql문))을 보여준다. -->\r\n");
      out.write("\t\t\t\t\t<td rowspan=\"2\" id = \"roomimg\"></td>\r\n");
      out.write("\t\t\t\t\t<td id = \"roomimg2\" style=\"margin-top: 10px\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id = \"roomimg3\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div id = \"pdMap\">\r\n");
      out.write("\t\t\t\t<div id=\"map\" style=\"width:700px;height:500px;margin-left: 400px\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"margin-left: 650px\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<button id = \"b2\" style=\"background-color:#007bff; color: white\"><span style=\"font-size: 20px\"> 편의시설 </span></button>\r\n");
      out.write("\t\t\t\t\t<button id = \"b3\" style=\"background-color:#007bff; color: white\"><span style=\"font-size: 20px\"> 안전시설 </span></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr style=\"width: 48.5%; margin-right: 350px\" color=\"#007bff\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer class=\"footer bg-light\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 h-100 text-center text-lg-left my-auto\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-inline mb-2\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"list-inline-item\"><a href=\"#\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"list-inline-item\">&sdot;</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"list-inline-item\"><a href=\"#\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"list-inline-item\">&sdot;</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"list-inline-item\"><a href=\"#\">Terms of Use</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"list-inline-item\">&sdot;</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"list-inline-item\"><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<p class=\"text-muted small mb-4 mb-lg-0\">&copy; Your Website\r\n");
      out.write("\t\t\t\t\t\t2020. All Rights Reserved.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 h-100 text-center text-lg-right my-auto\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-inline mb-0\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"list-inline-item mr-3\"><a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fab fa-facebook fa-2x fa-fw\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"list-inline-item mr-3\"><a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fab fa-twitter-square fa-2x fa-fw\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"list-inline-item\"><a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fab fa-instagram fa-2x fa-fw\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
