/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.64
 * Generated at: 2021-05-08 17:08:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ruser_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/kangjisoo/projects/JavaProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/2차프로젝트_최종본/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1615945974307L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Login</title>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            margin: 40px auto;\r\n");
      out.write("            line-height: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        h5 {\r\n");
      out.write("        \tfont-size: 20px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("        h5 span {\r\n");
      out.write("            color: rgb(18, 70, 184);\r\n");
      out.write("        }\r\n");
      out.write("        #login {\r\n");
      out.write("            background-color: rgb(18, 70, 184);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: 0;\r\n");
      out.write("            border-radius: 7px;\r\n");
      out.write("            padding: 20px 228px;\r\n");
      out.write("        }\r\n");
      out.write("        #signup {\r\n");
      out.write("            background-color: rgb(18, 70, 184);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: 0;\r\n");
      out.write("            border-radius: 7px;\r\n");
      out.write("            padding: 20px 221px;\r\n");
      out.write("        }\r\n");
      out.write("        #findpw {\r\n");
      out.write("            background-color: rgb(18, 70, 184);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: 0;\r\n");
      out.write("            border-radius: 7px;\r\n");
      out.write("            padding: 20px 208px;\r\n");
      out.write("        }\r\n");
      out.write("        input {\r\n");
      out.write("            border: 1px solid lightgray;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("        }\r\n");
      out.write("    \t</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/* $(function() {\r\n");
      out.write("\t$('#login').click(function() {\r\n");
      out.write("\t\tid = $('#id').val()\r\n");
      out.write("\t\tpw = $('#pw').val()\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (id == \"\") {\r\n");
      out.write("\t\t\talert('아이디를 입력하세요')\r\n");
      out.write("\t\t\t$(id).focus()\r\n");
      out.write("\t\t\treturn\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else if (pw == \"\") {\r\n");
      out.write("\t\t\talert('비밀번호를 입력하세요')\r\n");
      out.write("\t\t\t$(pw).focus()\r\n");
      out.write("\t\t\treturn\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\turl : \"ruser_login\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tid : id\r\n");
      out.write("\t\t\t\tpw : pw\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\tif (data == 'true') {\r\n");
      out.write("\t\t\t\t\tlocation.href = \"main.jsp\"\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$('#logincheck').html('<h6 style=color:red;>아이디나 비밀번호가 일치하지 않습니다.</h6>')\r\n");
      out.write("\t\t\t\t\t$('#id').focus()\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function() {\r\n");
      out.write("\t\t\t\talert(\"로그인 실패하였습니다.\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}) //ajax\r\n");
      out.write("\t\t\r\n");
      out.write("\t}) //idlogin\r\n");
      out.write("\t\r\n");
      out.write("\t$('#logout').click(function() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\turl: \"ruser_logout\",\r\n");
      out.write("\t\t\tsuccess: function() {\r\n");
      out.write("\t\t\t\tlocation.href = \"main.jsp\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function() {\r\n");
      out.write("\t\t\t\t alert(\"로그아웃 실패하였습니다.\")\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t}) //ajax\r\n");
      out.write("\t} //logout\r\n");
      out.write("}) //fun */\r\n");
      out.write("</script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h5><span>로그인</span></h5>\r\n");
      out.write("        <hr><br>\r\n");
      out.write("        \r\n");
      out.write("\t\t<form action=\"main\">\r\n");
      out.write("\t\t\t<div class=\"login\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"id\" placeholder=\"아이디\" name=\"userid\" required style=\"height:30px; width: 490px\"><br><br>\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"password\" id=\"pw\" placeholder=\"비밀번호\" name=\"userpw\" required style=\"height:30px; width: 490px\"><br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"logincheck\" style=\"float:left;\"></div>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"로그인\" id=\"login\"><br><br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<form action=\"signup\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"회원가입\" id=\"signup\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
