/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.64
 * Generated at: 2021-05-08 17:09:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mega.project.ProductVO;
import java.util.List;
import org.apache.jasper.tagplugins.jstl.core.ForEach;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/kangjisoo/projects/JavaProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/2차프로젝트_최종본/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1615945974307L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.ForEach");
    _jspx_imports_classes.add("com.mega.project.ProductVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<ProductVO> list = (List<ProductVO>)request.getAttribute("list");
	int listSize = list.size();
	session.setAttribute("listSize", listSize);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script>\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("  <title>내 집은 신촌에 있나방</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"resources/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom fonts for this template -->\r\n");
      out.write("  <link href=\"resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"resources/vendor/bootstrap/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"resources/vendor/fontawesome-free/css/all.min.css/vendor/simple-line-icons/css/simple-line-icons.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"resources/css/landing-page.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"resources/css/landing-page.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.k{\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Navigation : 맨 위 메뉴바 부분/ 모든 페이지에 공통적으로 들어갈 부분(메뉴바)-->\r\n");
      out.write("  <nav class=\"navbar navbar-light bg-light static-top\">\r\n");
      out.write("     <div class=\"logo\">\r\n");
      out.write("     <a class=\"navbar-brand\" href=\"main.jsp\">내 집은 신촌에 있나방</a>\r\n");
      out.write("     </div>\r\n");
      out.write("    <div id=\"menu\">\r\n");
      out.write("       <!-- 세션처리 -->\r\n");
      out.write("      ");
 if(session.getAttribute("userid") == null){ 
      out.write("\r\n");
      out.write("       <a class=\"btn btn-primary btn-lg\" href=\"productSummary.jsp\">방찾기</a>\r\n");
      out.write("       <a class=\"btn btn-primary btn-lg\" href=\"mypage_main.jsp\">마이페이지</a> <!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("       <a class=\"btn btn-primary btn-lg\" href=\"qnamain.jsp\">고객센터</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("       <a class=\"btn btn-primary btn-lg\" href=\"ruser_select.jsp\">회원정보검색</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("       <a class=\"btn btn-primary btn-lg\" href=\"ruser_select.jsp\">회원정보검색</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("      <a class=\"btn btn-primary btn-lg\" href=\"ruser_login.jsp\">로그인</a>\r\n");
      out.write("      <a class=\"btn btn-primary btn-lg\" href=\"signup.jsp\">회원가입</a>\r\n");
      out.write("      ");
 }else{ 
      out.write("\r\n");
      out.write("       <a class=\"btn btn-primary btn-lg\" href=\"productSummary.jsp\">방찾기</a>\r\n");
      out.write("       <a class=\"btn btn-primary btn-lg\" href=\"mypage_main.jsp\">마이페이지</a> <!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("       <a class=\"btn btn-primary btn-lg\" href=\"PMain.jsp\">방내놓기</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("       <a class=\"btn btn-primary btn-lg\" href=\"qnamain.jsp\">고객센터</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("       <a class=\"btn btn-primary btn-lg\" href=\"ruser_update.jsp\">회원정보수정</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("       <a class=\"btn btn-primary btn-lg\" href=\"ruser_select.jsp\">회원정보검색</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("       <a class=\"btn btn-primary btn-lg\" href=\"ruser_delete.jsp\">회원탈퇴</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("      <a class=\"btn btn-primary btn-lg\" href=\"ruser_logout.jsp\">로그아웃</a><!-- href에 각자 만든 페이지 주소 넣어주기 -->\r\n");
      out.write("      <div class=\"btn btn-primary btn-lg\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 환영합니다.</div>\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav><!-- navigation 종료 -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Masthead: 헤더부분 -->\r\n");
      out.write("  <header class=\"masthead text-white text-center\">\r\n");
      out.write("    <div class=\"overlay\"></div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-9 mx-auto\">\r\n");
      out.write("          <h1 class=\"mb-5\">어떤 방을 찾으세요?</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-10 col-lg-8 col-xl-7 mx-auto\">\r\n");
      out.write("          <form>\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("              <div class=\"col-12 col-md-9 mb-2 mb-md-0\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control form-control-lg\" placeholder=\"지역 또는 단지명을 입력하세요.\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-12 col-md-3\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-block btn-lg btn-primary\">방찾기</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("  <!-- Icons Grid : 섹션 영역-->\r\n");
      out.write("  \r\n");
      out.write("   ");
 if(listSize == 1){ 
      out.write(" \r\n");
      out.write("  <section class=\"features-icons bg-light text-center\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-4\">\r\n");
      out.write("          <div class=\"features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3\">\r\n");
      out.write("            <div class=\"features-icons-icon d-flex\">\r\n");
      out.write("              <i class=\"icon-screen-desktop m-auto text-primary\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <table style = \"width: 950px;\">\r\n");
      out.write("            \t<tr>\r\n");
      out.write("            \t\t<td style = \"width: 300px;\">\r\n");
      out.write("                  \t\t<a href=\"productdetail.jsp?pnum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].pnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"resources/rimg/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].roomimg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style = 'width: 300px; height: 300px'></a>\r\n");
      out.write("                  \t\t<h4 class=\"Room_Type and Price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].ptype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("                  \t\t<h5 class=\"Specific_info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].ctype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].rsize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].placetype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                  \t\t<h5 class=\"Place_info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].pinfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                  \t</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write(" ");
} 
      out.write("\r\n");
      out.write("     ");
 if(listSize == 2){ 
      out.write("\r\n");
      out.write("  <section class=\"features-icons bg-light text-center\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-4\">\r\n");
      out.write("          <div class=\"features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3\">\r\n");
      out.write("            <div class=\"features-icons-icon d-flex\">\r\n");
      out.write("              <i class=\"icon-screen-desktop m-auto text-primary\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <table style = \"width: 950px;\">\r\n");
      out.write("            \t<tr>\r\n");
      out.write("            \t\t<td style = \"width: 300px;\">\r\n");
      out.write("            \t\t\t<a href=\"productdetail.jsp?pnum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].pnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"resources/rimg/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].roomimg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style = 'width: 300px; height: 300px'></a>\r\n");
      out.write("                  \t\t<h4 class=\"Room_Type and Price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].ptype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("                  \t\t<h5 class=\"Specific_info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].ctype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].rsize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].placetype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                  \t\t<h5 class=\"Place_info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].pinfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("            \t\t</td>\r\n");
      out.write("            \t\t<td style = \"width: 10px;\">\r\n");
      out.write("            \t\t\t</td>\r\n");
      out.write("            \t\t<td style = \"width: 300px;\">\r\n");
      out.write("            \t\t\t<a href=\"productdetail.jsp?pnum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].pnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"resources/rimg/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].roomimg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style = 'width: 300px; height: 300px'></a>\r\n");
      out.write("                  \t\t<h4 class=\"Room_Type and Price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].ptype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("                  \t\t<h5 class=\"Specific_info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].ctype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].rsize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].placetype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                  \t\t<h5 class=\"Place_info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].pinfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("            \t\t</td>\r\n");
      out.write("            \t</tr>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  ");
} 
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("   ");
 if(listSize >= 3){ 
      out.write(" \r\n");
      out.write("  <section class=\"features-icons bg-light text-center\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-4\">\r\n");
      out.write("          <div class=\"features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3\">\r\n");
      out.write("            <div class=\"features-icons-icon d-flex\">\r\n");
      out.write("              <i class=\"icon-screen-desktop m-auto text-primary\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <table style = \"width: 950px;\">\r\n");
      out.write("            \t<tr>\r\n");
      out.write("            \t\t<td style = \"width: 300px;\">\r\n");
      out.write("                  \t\t<a href=\"productdetail.jsp?pnum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].pnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"resources/rimg/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].roomimg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style = 'width: 300px; height: 300px'></a>\r\n");
      out.write("                  \t\t<h4 class=\"Room_Type and Price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].ptype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("                  \t\t<h5 class=\"Specific_info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].ctype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].rsize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].placetype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                  \t\t<h5 class=\"Place_info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].pinfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                  \t</td>\r\n");
      out.write("                  \t<td style = \"width: 300px;\">\r\n");
      out.write("                   \t\t<a href=\"productdetail.jsp?pnum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].pnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"resources/rimg/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].roomimg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style = 'width: 300px; height: 300px'></a>\r\n");
      out.write("                 \t \t<h4 class=\"Room_Type and Price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].ptype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("                 \t \t<h5 class=\"Specific_info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].ctype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].rsize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].placetype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                  \t\t<h5 class=\"Place_info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1].pinfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                 \t</td>\r\n");
      out.write("                    <td style = \"width: 300px;\">\r\n");
      out.write("                    \t<a href=\"productdetail.jsp?pnum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[2].pnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"resources/rimg/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[2].roomimg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style = 'width: 300px; height: 300px'></a>\r\n");
      out.write("                  \t\t<h4 class=\"Room_Type and Price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[2].ptype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[2].price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("                  \t\t<h5 class=\"Specific_info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[2].ctype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[2].rsize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[2].placetype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                  \t\t<h5 class=\"Place_info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[2].pinfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  ");
} 
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <!-- Footer -->\r\n");
      out.write("   <footer class=\"footer bg-light\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-6 h-100 text-center text-lg-left my-auto\">\r\n");
      out.write("               <ul class=\"list-inline mb-2\">\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\">About</a></li>\r\n");
      out.write("                  <li class=\"list-inline-item\">&sdot;</li>\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\">Contact</a></li>\r\n");
      out.write("                  <li class=\"list-inline-item\">&sdot;</li>\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\">Terms of Use</a></li>\r\n");
      out.write("                  <li class=\"list-inline-item\">&sdot;</li>\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("               <p class=\"text-muted small mb-4 mb-lg-0\">&copy; Your Website\r\n");
      out.write("                  2020. All Rights Reserved.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 h-100 text-center text-lg-right my-auto\">\r\n");
      out.write("               <ul class=\"list-inline mb-0\">\r\n");
      out.write("                  <li class=\"list-inline-item mr-3\"><a href=\"#\"> <i\r\n");
      out.write("                        class=\"fab fa-facebook fa-2x fa-fw\"></i>\r\n");
      out.write("                  </a></li>\r\n");
      out.write("                  <li class=\"list-inline-item mr-3\"><a href=\"#\"> <i\r\n");
      out.write("                        class=\"fab fa-twitter-square fa-2x fa-fw\"></i>\r\n");
      out.write("                  </a></li>\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\"> <i\r\n");
      out.write("                        class=\"fab fa-instagram fa-2x fa-fw\"></i>\r\n");
      out.write("                  </a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </footer>\r\n");
      out.write("   <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
